### ISSUE TITLE
Is is not clear in the getting started that I have to compose. 

### ISSUE THREAD

**Issue by ozcanseker** [CrossBreezeNL/PowerDesigner-MDDE-Extension#26]
When I use the manual, it is not clear that I have to compose it.

When composing it is not clear that I have to use powershell 7.

**Comment by harmen-xb** [comment]
If this issue is for end-users, then as of the following commit, the getting started is updated to point to the releases. These are composed version of the extension in a zip file to make the process easier: https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/commit/0b9dc467336ef841295ef6e381c1d83e8b5f2ccf

If the comment is for contributors there is a contributing file references from the Readme now which explains the steps including the Powershell 7 dependency: https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/blob/main/CONTRIBUTING.md

Closing issue for now. If you which further changes, please re-open this issue.
